version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/gofiber/fiber/v2
    versions:
    - 2.4.0
    - 2.4.1
    - 2.5.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: monthly
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.11.2
    - 0.8.36
    - 0.8.38
    - 0.8.39
    - 0.8.41
    - 0.8.42
    - 0.8.43
    - 0.8.44
    - 0.8.46
    - 0.8.48
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
    - 3.36.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "00:00"
  open-pull-requests-limit: 10
