[run]
timeout = "5m"

[output]
sort-results = true

[linters]
presets = ["bugs", "error", "metalinter", "performance", "unused"]
disable = [
  "deadcode",
  "maligned",
  "rowserrcheck",
  "scopelint",
  "sqlclosecheck",
  "structcheck",
  "varcheck",
  "wrapcheck",
  "noctx",
  "revive",
]

[linters-settings.govet]
enable-all = true
disable = ["shadow", "fieldalignment"]

[linters-settings.errcheck]
check-type-assertions = false

[linters-settings.gocritic]
enabled-tags = [
  "diagnostic",
  "style",
  "performance",
  "experimental",
  "opinionated",
]
disabled-checks = [
  "commentedOutCode",
  "ifElseChain",
  "paramTypeCombine",
  "sprintfQuotedString",
  "unnamedResult",
  "whyNoLint",
]
