[run]
timeout = "5m"

[output]
sort-results = true

[linters]
presets = [
	"bugs",
	"comment",
	# "complexity",
	"error",
	"format",
	"import",
	"metalinter",
	# "module",
	"performance",
	"sql",
	# "style",
	"test",
	"unused",
]
disable = [
	"exhaustruct",
	"gci",
	"godox",
	"musttag",
	"paralleltest",
	"revive",
	"wrapcheck",
	"depguard",
]

[linters-settings.govet]
enable-all = true
disable = ["fieldalignment"]

[linters-settings.errcheck]
check-type-assertions = false

[linters-settings.gocritic]
enabled-tags = [
	"diagnostic",
	"style",
	"performance",
	"experimental",
	"opinionated",
]
disabled-checks = [
	"commentedOutCode",
	"ifElseChain",
	"paramTypeCombine",
	"sprintfQuotedString",
	"unnamedResult",
	"whyNoLint",
	"sloppyReassign",
]
