# https://fly.io/docs/reference/configuration/

app = "feedbox"

[build]
# https://paketo.io/docs/concepts/builders/#what-paketo-builders-are-available
builder = "paketobuildpacks/builder:full"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[deploy]
release_command = "migrate up"

[processes]
web = "server"
worker = "worker"

[env]
ENV = "prod"
SERVER = "https://feedbox.h11.io"
PORT = "8000"
MAILGUN_DOMAIN = "feedbox.h11.io"
MAILGUN_FROM = "FeedBox <bot@feedbox.h11.io>"
TELEGRAM_BOT_NAME = "FeedBoxBot"
DATABASE_URL = "/data/database/feedbox.db"

[mounts]
source = "sqlite"
destination = "/data/database"

[[services]]
internal_port = 8000
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = "80"
