[build]
base = "web/"
publish = "web/_build/"
command = "yarn run build"

[build.environment]
NODE_VERSION = "10"
YARN_VERSION = "1.17.0"
SITE = "https://feedbox.h11.io"
API = "https://feedbox.h11.io"

[[redirects]]
from = "/api/*"
to = "https://fbox.herokuapp.com/api/:splat"
status = 200
force = false
