version: 1
update_configs:
    - package_manager: "javascript"
      directory: "/server"
      update_schedule: "weekly"
    - package_manager: "javascript"
      directory: "/web"
      update_schedule: "weekly"
    - package_manager: "javascript"
      directory: "/worker"
      update_schedule: "weekly"
