BEGIN;

ALTER TABLE users
ALTER COLUMN platform TYPE VARCHAR(64),
ALTER COLUMN pid TYPE VARCHAR(256);

ALTER TABLE feeds
ALTER COLUMN url TYPE VARCHAR(2048),
ALTER COLUMN link TYPE VARCHAR(2000)[];

COMMIT;
