BEGIN;

ALTER TABLE users
	ALTER COLUMN platform TYPE TEXT COLLATE "C",
	ALTER COLUMN pid TYPE TEXT COLLATE "C";

ALTER TABLE feeds
	ALTER COLUMN url TYPE TEXT COLLATE "C",
	ALTER COLUMN link TYPE TEXT[] COLLATE "C";

COMMIT;
