name: deploy

on:
    push:
        branches:
            - master

jobs:
    heroku:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2.0.0
            - uses: actions/setup-node@v1.1.0
              with:
                  version: "13.x"
            - name: yarn-cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1.1.2
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-
            - run: yarn install
            - run: make test
              env:
                  NODE_ENV: "development"
                  SERVER: "http://localhost:8000"
                  COOKIE_SECRET: "crypto.randomBytes(2).toString('hex')"
                  GITHUB_AUTH_SECRET: "crypto.randomBytes(2).toString('hex')"
                  GITHUB_CLIENT_ID: "https://github.com/settings/developers"
                  GITHUB_CLIENT_SECRET: "https://github.com/settings/developers"
                  MAILGUN_API_KEY: "key-example"
                  MAILGUN_DOMAIN: "feedbox.example.com"
                  MAILGUN_FROM: "feedbox <feedbox@example.com>"
                  ROLLBAR_TOKEN: "https://rollbar.com"
                  DATABASE_URL: "postgres://example"
            - uses: codecov/codecov-action@v1.0.5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./server/coverage/coverage-final.json
            - name: push to heroku
              run: git push --force https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git || echo
              env:
                  HEROKU_APP_NAME: "fbox"
                  HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
