name: deploy

on:
    push:
        branches:
            - master

jobs:
    heroku:
        runs-on: ubuntu-20.04
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: feedbox
                ports: ['5432:5432']
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v2.3.1
              with:
                  fetch-depth: 0
            - uses: actions/setup-go@v2.1.2
              with:
                  go-version: '1.x'
            - uses: actions/cache@v2.1.1
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: ${{ runner.os }}-go-
            - run: make test
              env:
                  ENV: 'test'
                  SERVER: 'http://localhost:8000'
                  PORT: '8000'
                  COOKIE_SECRET: '679aa943a570ed1d5c9be2a4ba2b9c4e6150564f6043cfc45d4ceb9dc9d626fe'
                  GITHUB_CLIENT_ID: 'https://github.com/settings/developers'
                  GITHUB_CLIENT_SECRET: 'https://github.com/settings/developers'
                  MAILGUN_API_KEY: 'key-example'
                  MAILGUN_DOMAIN: 'feedbox.example.com'
                  MAILGUN_FROM: 'feedbox <feedbox@example.com>'
                  TELEGRAM_BOT_TOKEN: '123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11'
                  TELEGRAM_BOT_NAME: 'bot_name'
                  ROLLBAR_TOKEN: 'post_server_item'
                  DATABASE_URL: 'postgres://user:password@localhost:5432/feedbox?sslmode=disable'
            - name: deploy heroku
              run: git push --force https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git || echo
              env:
                  HEROKU_APP_NAME: 'fbox'
                  HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
