name: feedbox-server

on:
    push:
        branches:
            - master
        paths:
            - '.github/workflows/server.yml'
            - 'server/**'

jobs:
    build-deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2.0.0
            - name: push to heroku
              run: git subtree push --prefix=server https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git master
              env:
                  HEROKU_APP_NAME: "fbox"
                  HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
