name: feedbox-worker

on:
    push:
        branches:
            - master
        paths:
            - '.github/workflows/worker.yml'
            - 'worker/**'

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2.0.0
            - uses: actions/setup-node@v1.1.0
              with:
                  version: "13.x"
            - name: yarn-cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1.1.2
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-
            - name: deploy
              working-directory: ./worker
              run: |
                yarn add @cloudflare/wrangler
                yarn wrangler publish
              env:
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
